version: '3'

volumes:
  db-data:

services:
  rundeck:
    hostname: ${RD_HOSTNAME}
    build:
      context: ${RD_CONTEXT}
      args:
        IMAGE: ${IMAGE}
    ports:
      - ${RD_PORT}:4440
  database:
    hostname: ${DB_HOSTNAME}
    build:
      context: ${DB_CONTEXT}
      args:
        IMAGE: ${DB_IMAGE}
        DB_HOSTNAME: ${DB_HOSTNAME}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - ${DB_PORT}:3306