version: '3'

services:
  rundeck:
    hostname: rundeck
    build:
      context: ${RD_CONTEXT}
      args:
        IMAGE: ${IMAGE}
        RD_PASSWORD: ${RD_PASSWORD}
        DB_HOSTNAME: ${DB_HOSTNAME}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_JDBC_URL: ${DB_JDBC_URL}
        DB_JDBC_DRIVER: ${DB_JDBC_DRIVER}
    ports:
      - ${RD_PORT}:4440
    links:
      - database
    depends_on:
      - database
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  database:
    hostname: database
    build:
      context: ${DB_CONTEXT}
      args:
        IMAGE: ${DB_IMAGE}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - ${DB_PORT}:3306
