version: "3"
services:
  rundeck:
    hostname: ${RD_HOSTNAME}
    build:
      context: ${RD_CONTEXT}
      args:
        IMAGE: ${RD_IMAGE}
    deploy:
      resources:
        limits:
          memory: ${RD_MEM}
    links:
      - oracle
    ports:
      - ${RD_PORT_01}:4440
    environment:
      RUNDECK_GRAILS_URL: ${RD_PROTOCOL}://${RD_HOSTNAME}
      RUNDECK_SERVER_FORWARDED: 'true'
      RUNDECK_DATABASE_DRIVER: ${RD_JDBC_DRIVER}
      RUNDECK_DATABASE_USERNAME: ${DB_USER}
      RUNDECK_DATABASE_PASSWORD: ${DB_PASS}
      RUNDECK_DATABASE_URL: jdbc:oracle:thin:@oracle:1521:XE
      RUNDECK_FEATURE_PAGEDJOBLIST_ENABLED: 'true'
  oracle:
    hostname: ${DB_HOSTNAME}
    build:
      context: ${DB_CONTEXT}
    ports:
      - 1521:1521
      - 5500:5500
    expose:
      - 1521
      - 5500
    volumes:
       - ./scripts:/opt/oracle/scripts/startup