#!/bin/bash
#############################################
echo "Rundeck Server hostname:"; read -r rundeckServer
echo -e "\nRundeck username:"; read -r rundeckUser
echo -e "\nRundeck password:"; read -r rundeckPass
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
# rundeckServer="http://localhost:4440"
# rundeckUser="admin"
# rundeckPass="admin"
#############################################
# Options Variables
#############################################
apiVersion="17"
apiFormat="json"
jobFormat="yaml"
curlOptions="-s"
cookie="cookie"
#############################################
mkdir -p exported_projects

curl -X "POST" "$curlOptions" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c "$cookie" -b "$cookie" "$rundeckServer"/j_security_check

for projectName in $(curl -X "GET" "$curlOptions" -H "Accept: application/$apiFormat" -H "Content-Type: application/$apiFormat" -b "$cookie" "$rundeckServer"/api/"$apiVersion"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
mkdir -p exported_projects/"$projectName"
mkdir -p exported_projects/"$projectName"/jobs
curl "$curlOptions" -X "GET" -H "Accept: application/$apiFormat" -H "Content-Type: application/$apiFormat" -b "$cookie" "$rundeckServer"/api/"$apiVersion"/project/"$projectName"/config > exported_projects/"$projectName"/"$projectName".project
for jobId in $(curl "$curlOptions" -X "GET" -H "Accept: application/$apiFormat" -H "Content-Type: application/$apiFormat" -b "$cookie" "$rundeckServer"/api/"$apiVersion"/project/"$projectName"/jobs | sed 's/,/\n/g' | grep id | cut -d ":" -f2 | tr -d '"')
do
curl "$curlOptions" -X "GET" -H "Accept: application/$jobFormat" -H "Content-Type: application/$jobFormat" -b "$cookie" "$rundeckServer"/api/"$apiVersion"/job/"$jobId" > exported_projects/"$projectName"/jobs/"$jobId".yaml;
done
done

rm -f $cookie

echo -e "\n[ Please go to ""exported_projects"" folder ]"