#!/bin/bash

rundeckServer="http://localhost:4440"
rundeckUser="admin"
rundeckPass="admin"
cookie="cookie"

curl -s -X "POST" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c "$cookie" -b "$cookie" "$rundeckServer"/j_security_check

rm -f $cookie