#!/bin/bash

rundeckServer="http://node01-linux.local:4440"
rundeckUser="admin"
rundeckPass="admin"
executionID="$1"

curl -s -X "POST" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c cookie -b cookie "$rundeckServer"/j_security_check

curl -s -X "GET" --header "Content-Type: application/json" --header "Accept: application/json" -b cookie "$rundeckServer"/api/39/execution/"$executionID" | jq .

rm -f cookie
