apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: run2596
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "Pa$$w0rd!"
        - name: "MYSQL_DATABASE"
          value: rundeck
        - name: "MYSQL_USER"
          value: rundeckuser
        - name: "MYSQL_PASSWORD"
          value: "rundeckpassword"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
