#!/bin/bash
#############################################
echo "Insert the Rundeck Server hostname:"; read -r serverHost
echo -e "\nWhich port?:"; read -r serverPort
echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
# serverHost="localhost"
# serverPort="4440"
# token="CJZUZ36yMZmXLQjxOr8VdE8V2WrOanvm"
apiVersion=24
options="exportAll=true"
# options="exportJobs=true"
# options="$options&exportExecutions=true"
# options="$options&exportConfigs=true"
# options="$options&exportReadmes=true"
# options="$options&exportAcls=true"
#############################################
mkdir -p exported_projects
for i in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
curl -s -X "GET" -H "Accept: application/zip" -H "Content-Type: application/zip" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/project/"$i"/export?"$options" > exported_projects/"$i".jar
done
echo -e "\n[ Please go to ""exported_projects"" folder ]"
