#!/bin/bash
#############################################
# echo "Insert the Rundeck Server hostname:"; read -r server_host
# echo -e "\nWhich port?:"; read -r server_port
# echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
server_host="localhost"
server_port="4440"
token="AeqcX0xnywayfxbO4IrDNb3E9GwMA9tW"
api_version=28
#############################################
mkdir exported_projects
for i in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
mkdir exported_projects/"$i"
mkdir exported_projects/"$i"/jobs
curl -s -X "GET" -H "Accept: application/xml" -H "Content-Type: application/xml" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/project/"$i"/config > exported_projects/"$i"/"$i".project
for n in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/project/"$i"/jobs | sed 's/,/\n/g' | grep id | cut -d ":" -f2 | tr -d '"')
do
curl -s -X "GET" -H "Accept: application/yaml" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/job/"$n" > exported_projects/"$i"/jobs/"$n".yaml;
done
done

echo -e "\n\n[ Please go to ""exported_projects"" folder ]"
