#!/bin/bash
#############################################
# echo "Insert the Rundeck Server hostname:"; read -r serverHost
# echo -e "\nWhich port?:"; read -r serverPort
# echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
# serverHost="localhost"
# serverPort="4440"
# token="AeqcX0xnywayfxbO4IrDNb3E9GwMA9tW"
apiVersion=28
#############################################
mkdir -p exported_projects
for projectName in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
mkdir -p exported_projects/"$projectName"
mkdir -p exported_projects/"$projectName"/jobs
curl -s -X "GET" -H "Accept: application/xml" -H "Content-Type: application/xml" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/project/"$projectName"/config > exported_projects/"$projectName"/"$projectName".project
for jobId in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/project/"$projectName"/jobs | sed 's/,/\n/g' | grep id | cut -d ":" -f2 | tr -d '"')
do
curl -s -X "GET" -H "Accept: application/yaml" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/job/"jobId" > exported_projects/"$projectName"/jobs/"jobId".yaml;
done
done

echo -e "\n[ Please go to ""exported_projects"" folder ]"
