#!/bin/bash
#############################################
echo
echo "Rundeck Server url:(e.g. http://rundeck.local:4440)"; read -r rundeckServer
echo -e "\nRundeck Server Username:"; read -r rundeckUser
echo -e "\nRundeck Server Password:"; read -r rundeckPass
echo
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
#rundeckServer="http://rundeck.local:4440"
#rundeckUser="admin"
#rundeckPass="admin"
apiVersion=34
options="exportAll=false"
options="$options&exportJobs=true"
options="$options&exportExecutions=true"
options="$options&exportConfigs=true"
options="$options&exportReadmes=true"
options="$options&exportAcls=true"
options="$options&exportScm=true"
options="$options&exportWebhooks=true"
options="$options&whkIncludeAuthTokens=true"
#############################################
echo "Downloading data..."
mkdir -p exported_projects

curl -s -X "POST" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c cookie "$rundeckServer"/j_security_check

for projectName in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -b cookie "$rundeckServer"/api/"$apiVersion"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
curl -s -X "GET" -H "Accept: application/zip" -H "Content-Type: application/zip" -b cookie "$rundeckServer"/api/"$apiVersion"/project/"$projectName"/export?"$options" > exported_projects/"$projectName".jar
done
echo -e "\n[ Please go to ""exported_projects"" folder ]"

rm -f cookie