#!/bin/bash
#############################################
# echo "Insert the Rundeck Server hostname:"; read -r server_host
# echo -e "\nWhich port?:"; read -r server_port
# echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
server_host="localhost"
server_port="4440"
token="AeqcX0xnywayfxbO4IrDNb3E9GwMA9tW"
api_version=28
options="exportAll=true"
# options="exportJobs=true"
# options="$options&exportExecutions=true"
# options="$options&exportConfigs=true"
# options="$options&exportReadmes=true"
# options="$options&exportAcls=true"
#############################################
mkdir exported_projects
for i in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/projects|sed 's/,/\n/g'| grep name | cut -d ":" -f2 | tr -d '"')
do
curl -s -X "GET" -H "Accept: application/zip" -H "Content-Type: application/zip" -H "X-Rundeck-Auth-Token: $token" http://"$server_host":"$server_port"/api/"$api_version"/project/"$i"/export?"$options" > exported_projects/"$i".jar
done
echo -e "\n\n[ Please go to ""exported_projects"" folder ]"
