#!/bin/bash

rundeckServer="http://node01-linux.local:4440"
rundeckUser="admin"
rundeckPass="admin"

curl -X "POST" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c cookie -b cookie "$rundeckServer"/j_security_check

curl -X "GET" --header "Content-Type: application/json" --header "Accept: application/json" -b cookie "$rundeckServer"/api/39/system/info

rm -f cookie
