#!/bin/bash
#############################################
# echo "Insert the Rundeck Server hostname:"; read -r serverHost
# echo -e "\nWhich port?:"; read -r serverPort
# echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
# serverHost="localhost"
# serverPort="4440"
# token="AeqcX0xnywayfxbO4IrDNb3E9GwMA9tW"
apiVersion=17
options="exportAll=true"
# options="exportJobs=true"
# options="$options&exportExecutions=true"
# options="$options&exportConfigs=true"
# options="$options&exportReadmes=true"
# options="$options&exportAcls=true"
#############################################
for keyUrl in $(curl -s -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" http://"$serverHost":"$serverPort"/api/"$apiVersion"/storage/keys|sed 's/,/\n/g'|grep url|sed 's/.*http/http/g'|tr -d '"')
do
echo "$keyUrl"
done
