#!/bin/bash

#############################################
echo "This Script queries failed jobs on N hours, days, etc (please see docs recentFilter)."
echo "Please fill the following:"
#############################################
echo -e "\nRundeck Server URL:(e.g. http://rundeck.local:4440)"; read -r rundeckServer
echo -e "\nRundeck User:"; read -r rundeckUser
echo -e "\nRundeck Pass:"; read -r rundeckPass
echo -e "\nRundeck Project:"; read -r projectName
echo -e "\nHow much time do you want to filter?:"; read -r timeFilter
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
#rundeckServer=http://node01-linux.local:4440
#rundeckUser=admin
#rundeckPass=admin
#projectName=IssuesTesting
#timeFilter=1d
#############################################
apiVersion=23
outputFormat=json
cookie=cookie
curlOption=-s

curl $curlOption -X "POST" -d "j_username=$rundeckUser" -d "j_password=$rundeckPass" -c cookie -b cookie "$rundeckServer"/j_security_check

for jobID in $(curl $curlOption -X "GET" -b "$cookie" -c "$cookie" -H "Accept: application/$outputFormat" -H "Content-Type: application/$outputFormat" "$rundeckServer/api/$apiVersion/project/$projectName/jobs" | sed 's/,/\n/g' | grep id | cut -d ":" -f2 | tr -d '"')
do
curl $curlOption -X "GET" -b "$cookie" -c "$cookie" -H "Accept: application/$outputFormat" -H "Content-Type: application/$outputFormat" "$rundeckServer/api/$apiVersion/project/$projectName/executions?statusFilter=failed&recentFilter=$timeFilter&max=1&jobIdListFilter=$jobID" | jq .
done

rm -f "$cookie"