#!/bin/bash
#############################################
# echo "Insert the Rundeck Server url:(e.g. http://rundeck.local:4440)"; read -r rundeckServer
# echo -e "\nCopy and Paste the Rundeck API Token:"; read -r token
#############################################
# to run unatended mode, please comment the code above and uncomment the code below, and replace with your props
#############################################
rundeckServer="http://node01-linux.local:4440"
token="zKvgVUWcC7AluCN5F7sCW7jPJhYtz4Lv"
apiVersion=17
options="exportAll=true"
# options="exportJobs=true"
# options="$options&exportExecutions=true"
# options="$options&exportConfigs=true"
# options="$options&exportReadmes=true"
# options="$options&exportAcls=true"
#############################################

projectName="$(echo $1|rev|cut -d "/" -f1|rev|cut -d "-" -f1)"
echo $projectName

curl -s -X "POST" -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Rundeck-Auth-Token: $token" "$rundeckServer"/api/"$apiVersion"/projects -d '{ "name": "'$projectName'" }'|jq

curl -s -X "PUT" -H "Accept: application/json" -H "Content-Type: application/zip" -H "X-Rundeck-Auth-Token: $token" "$rundeckServer"/api/"$apiVersion"/project/"$projectName"/import -T "$1"|jq